#1
language: node_js
node_js:
  - 8

script: skip 

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_API_KEY  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  repo: fabian-portillo/fabian-portillo.github.io
  local-dir: $TRAVIS_BUILD_DIR
  on:
    branch: master
    
after_success: |
  if [ -n "$GITHUB_API_KEY" ]; then
    cd "$TRAVIS_BUILD_DIR"
    # This generates a `web` directory containing the website.
    make web
    cd web
    git init
    git add .
    git -c user.name='travis' -c user.email='travis' commit -m init
    # Make sure to make the output quiet, or else the API token will leak!
    # This works because the API key can replace your password.
    git push -f -q https://fabian-portillo:$GITHUB_API_KEY@github.com/fabian-portillo/fabian-portillo.github.io-master master &>/dev/null
    cd "$TRAVIS_BUILD_DIR"
  fi
    
cache:
  directories:
    - "node_modules"

branches:
  only:
  - master
